# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Emily Wenger
description: >- # this means to ignore newlines until "baseurl:"
  Emily Wenger's personal website.
baseurl: "" #"/" #"/emilywenger.github.io" # the subpath of the site
url: "https://www.emilywenger.com" #"https://emilywenger.github.io" # the base hostname & protocol for the site
og_image: /assets/img/ewenger_headshot.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: Teaching
    - name: News
    - name: CV
      slug: /assets/CV.pdf

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: emily.wenger@duke.edu
      link: mailto:emily.wenger@duke.edu
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/ewillson
    - name: GitHub
      link: http://github.com/emilywenger

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
