# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Emily Wenger
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/personal_website" # the subpath of the site
url: "https://emilywenger.github.io" # the base hostname & protocol for the site
og_image: /assets/img/emily-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: News
    - name: CV
      slug: /assets/CV.pdf

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: ewenger@uchicago.edu
      link: mailto:ewenger@uchicago.edu
  follow:
    - name: Twitter
      link: http://twitter.com/em_wenger
      username: "@em_wenger"
    - name: Facebook
      link: http://facebook.com/EmilyWenger
    - name: LinkedIn
      link: http://linkedin.com/in/ewillson
    - name: GitHub
      link: http://github.com/emilywenger

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
